name: "push message"
# Default to bash
defaults:
  run:
    shell: bash

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: variables
        run: echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  bad:
    runs-on: ubuntu-latest
    steps:
      - name: a failure
        run: exit 0
  notify-success:
    runs-on: ubuntu-latest
    needs: [output, bad]
    if: success()
    steps:
      - name: Send Success Notification
        run: |
          curl --location ${{ secrets.NOTIFICATION_URL }} \
               --header 'Content-Type: application/json' \
               --data-raw "
                 {
                   \"content\": \"<@${{ secrets.NOTIFICATION_USER_ID }}>\",
                   \"allowed_mentions\": {
                     \"parse\": [\"users\"]
                   },
                   \"embeds\": [
                     {
                       \"color\": 11162547,
                       \"title\": \"Workflow Success\",
                       \"url\": \"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\",
                       \"description\": \"Successfully deployed [STC-Hub](https://stcentral-hub.github.io/ 'STCentral-Hub')\",
                       \"thumbnail\": {
                         \"url\": \"https://github.com/STCentral-Hub/stcentral-hub.github.io/raw/main/static/workflow_success.png\"
                       },
                       \"author\": {
                         \"name\": \"STCentral-Hub\",
                         \"url\": \"https://github.com/STCentral-Hub/stcentral-hub.github.io\",
                         \"icon_url\": \"https://avatars.githubusercontent.com/u/120429077?v=4\"
                       }
                     }
                   ]
                 }"
  notify-failure:
    runs-on: ubuntu-latest
    needs: [output, bad]
    if: failure()
    steps:
      - name: Send Failure Notification
        run: |
          curl --location ${{ secrets.NOTIFICATION_URL }} \
               --header 'Content-Type: application/json' \
               --data-raw "
                 {
                   \"content\": \"<@${{ secrets.NOTIFICATION_USER_ID }}>\",
                   \"allowed_mentions\": {
                     \"parse\": [\"users\"]
                   },
                   \"embeds\": [
                     {
                       \"color\": 11162547,
                       \"title\": \"Workflow Failure\",
                       \"url\": \"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\",
                       \"description\": \"[STC-Hub](https://stcentral-hub.github.io/ 'STCentral-Hub') failed to deploy and may be offline\",
                       \"thumbnail\": {
                         \"url\": \"https://github.com/STCentral-Hub/stcentral-hub.github.io/raw/main/static/workflow_failure.png\"
                       },
                       \"author\": {
                         \"name\": \"STCentral-Hub\",
                         \"url\": \"https://github.com/STCentral-Hub/stcentral-hub.github.io\",
                         \"icon_url\": \"https://avatars.githubusercontent.com/u/120429077?v=4\"
                       }
                     }
                   ]
                 }"
