name: "push message"
# Default to bash
defaults:
  run:
    shell: bash

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:  
  bad:
    runs-on: ubuntu-latest
    steps:
      - name: a failure
        run: exit 1
  send:
    if: failure()
    needs: [bad]
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
          curl --location ${{ secrets.DC }} \
               --header 'Content-Type: application/json' \
               --data-raw ${{ secrets.SUCCESS_MESSAGE }}
